#include <stdio.h>
int main() {
    char state1[20], state2[20], cityname1[20], cityname2[20], chartercode1[10], chartercode2[10] = "standart";
    int population1, population2, turisticpoints1, turisticpoints2 = 0;
    float area1, area2, PIB1, PIB2 = 0.0;

        printf("Super Trunfo - Cartas de Cidades Brasileiras\n");
            printf("\n");
                printf("Carta 1:\n");
                printf("\n Estado: ");
                    scanf("%s", state1);
                printf("\n Código: ");
                    scanf("%s", chartercode1);
                printf("\n Nome da cidade: ");
                    scanf("%s", cityname1);
                printf("\n População: ");
                    scanf("%d", &population1);
                printf("\n Área (em km²): ");
                    scanf("%f", &area1);
                printf("\n PIB: ");
                    scanf("%f", &PIB1);
                printf("\n Número de pontos turísticos: ");
                    scanf("%d", &turisticpoints1);
            printf("\n");
                printf("Carta 2:\n");
                printf("\n Estado: ");
                    scanf("%s", state2);
                printf("\n Código: ");
                    scanf("%s", chartercode2);
                printf("\n Nome da cidade: ");
                    scanf("%s", cityname2);
                printf("\n População: ");
                    scanf("%d", &population2);
                printf("\n Área (em km²): ");
                    scanf("%f", &area2);
                printf("\n PIB: ");
                    scanf("%f", &PIB2);
                printf("\n Número de pontos turísticos: ");
                    scanf("%d", &turisticpoints2);
            printf("\n");
        printf("Carta 1:\n");
            printf("Estado: %s\n", state1);
            printf("Código: %s\n", chartercode1);
            printf("Nome da cidade: %s\n", cityname1);
            printf("População: %d mil habitantes\n", population1);
            printf("Área: %.2f km²\n", area1);
            printf("PIB: %.2f\n", PIB1);
            printf("Número de pontos turísticos: %d\n", turisticpoints1);
        printf("\n");
            printf("Carta 2:\n");
            printf("Estado: %s\n", state2);
            printf("Código: %s\n", chartercode2);
            printf("Nome da cidade: %s\n", cityname2);
            printf("População: %d mil habitantes\n", population2);
            printf("Área: %.2f km²\n", area2);
            printf("PIB: %.2f\n", PIB2);
            printf("Número de pontos turísticos: %d\n", turisticpoints2);
        printf("\n");
        printf("Fim do Super Trunfo\n");
    return 0;
}